apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring-system
spec:
  releaseName: prometheus
  chart:
    git: https://charts.helm.sh/stable
    ref: master
    path: stable/appmesh-prometheus
  values:
    retention: 2h
    fullnameOverride: prometheus
